services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: taxislibres
        POSTGRES_PASSWORD: taxislibres
        POSTGRES_DB: taxislibres
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: